name: main
on:
  pull_request:
   branches:
     - main
     - develop1
     - develop2
     - master
     - master1
     - master2
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v3
     - name: Checkmarx AST CLI Action
       uses: checkmarx/ast-github-action@main #Github Action version
       with:
         project_name: ${{ github.repository }}
         cx_tenant: nfr_trustdimension
         base_uri: https://ast.checkmarx.net
         cx_client_id: ${{ secrets.CLIENT_ID }}
         cx_client_secret: ${{ secrets.SECRET }}
         #branch: ${{ github.ref }}
         #branch: ${{ github.ref#refs/heads/}}
         if: github.event_name == 'pull_request'
         run: echo "Branch name is $GITHUB_HEAD_REF"
         additional_params:
          --threshold "sast-critical=1; sast-high=100; sast-medium=100; sca-critical=1; sca-high=100;iac-security-medium=1"
          --project-tags tag1,tag2,tag3
          --tags tag
          --timeout 10000 
          --scan-timeout 10000

